### PR TITLE
Decoding function for packed felts

### PR DESCRIPTION
**Pull request by Orland0x**
We now pack the timestamps in the proposal struct in the space contract to save gas. 
https://github.com/snapshot-labs/sx-core/blob/pack_proposal_struct/contracts/starknet/lib/proposal.cairo
Use this function to decode the packed value into the 4 timestamps

### CODE REVIEW

**Comment by bonustrack** [comment]
@Orland0x Can we close this PR? Doesn't seem to be used

**Comment by Orland0x** [comment]
> @Orland0x Can we close this PR? Doesn't seem to be used

yes - I'm assuming @Sekhmet implemented something else to decode the timestamps?

**Comment by Sekhmet** [comment]
@Orland0x at sx-api only, not in this library:
https://github.com/snapshot-labs/sx-api/blob/3d7de4d09727e3388c4a9899693beae7b3fb2caa/src/utils.ts#L43-L50

**Comment by bonustrack** [comment]
Looks good so I'm closing this PR

**Pull request closed without merging**
