### PR TITLE
feat: fetch real block from network for votes and proposals

### PR DESCRIPTION
**Pull request by Sekhmet**
Depends on #82

- Get rid of `Metadata` - block requirement is something specific to singleSlotProof so it doesn't make sense to make it global and waste extra requests (we are already doing quite few of them, but they are quite fast (100-150ms), at least compared to contract calls).
- When creating proposal fetch latest L1 block.
- When voting fetch block associated to timestamp of proposal.
- Had to upgrade eslint so it doesn't crash processing `Promise<[string, string]>`.

## Test plan
- Create proposal with `ethSig + SSP`
- Vote with `ethSig + SSP`

### CODE REVIEW

**Comment by bonustrack** [comment]
I've asked mana to process the block `7574500` which went well, but I tried a propose after that and got a contract exception, see error:

```sh
  ● StarkNetTx › ethSig authenticator + single slot proof › StarkNetTx.propose()

    GatewayError: Error at pc=0:32:
    Got an exception while executing a hint.
    Cairo traceback (most recent call last):
    Unknown location (pc=0:502)
    Unknown location (pc=0:461)
    Unknown location (pc=0:518)
```

**Comment by bonustrack** [comment]
I just tried again to do a `propose` with a new block `7574600` and it worked here is the tx https://goerli.voyager.online/tx/0x4a149cce5a579beb4d85b52f6af039021bcd585d9e4901447e394d7da0b7d4e . Perhaps in my previous attempt the block was not yet process on L2, I noticed that even if process is not complete Fossil contract show the latest sent block here https://goerli.voyager.online/contract/0x6ca3d25e901ce1fff2a7dd4079a24ff63ca6bbf8ba956efc71c1467975ab78f#readContract

**Comment by bonustrack** [comment]
Vote went well too (on the newly created proposal) https://goerli.voyager.online/tx/0x64b164279d6724b23f37e633d1fb5dd01f9c0800a94bfb6c3c4ab23df918b82

**Review by bonustrack — APPROVED** [review]

**Comment by Sekhmet** [comment]
Tests will start failing as we moved latest L1 block and tests no longer match up.
I'm working on mocking those requests so tests don't depend on real network state.

**Pull request merged**
